version: '2'

services:
    graphql:
        build: docker/php7-fpm
        env_file: .env
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/${PROJECT_NAME}:cached
            - ${SYMFONY_APP_PATH}/var/logs:/var/www/${PROJECT_NAME}/var/logs:cached
    nginx:
        build: docker/nginx
        ports:
            - ${NGINX_PORT}:80
        volumes:
            - ./logs/nginx/:/var/log/nginx:cached
        volumes_from:
            - graphql

volumes:
    data:
